// <auto-generated />
using Clipify.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clipify.Persistence.Migrations
{
    [DbContext(typeof(ClipifyDbContext))]
    [Migration("20260727160525_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Clipify.Persistence.Entities.MediaArtifactEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUnixMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_media_artifacts_job");

                    b.ToTable("media_artifacts", (string)null);
                });

            modelBuilder.Entity("Clipify.Persistence.Entities.MediaJobEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CancelRequestedAtUnixMs")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompletedAtUnixMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtUnixMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<long?>("HeartbeatAtUnixMs")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LeaseAcquiredAtUnixMs")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LeaseExpiresAtUnixMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentJobId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProgressJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RetryOfJobId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long?>("StartedAtUnixMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUnixMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkflowId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUnixMs")
                        .HasDatabaseName("ix_media_jobs_created");

                    b.HasIndex("LeaseExpiresAtUnixMs")
                        .HasDatabaseName("ix_media_jobs_lease_expires");

                    b.HasIndex("State", "Priority", "CreatedAtUnixMs", "Id")
                        .HasDatabaseName("ix_media_jobs_queue");

                    b.ToTable("media_jobs", (string)null);
                });

            modelBuilder.Entity("Clipify.Persistence.Entities.MediaArtifactEntity", b =>
                {
                    b.HasOne("Clipify.Persistence.Entities.MediaJobEntity", "Job")
                        .WithMany("Artifacts")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Clipify.Persistence.Entities.MediaJobEntity", b =>
                {
                    b.Navigation("Artifacts");
                });
#pragma warning restore 612, 618
        }
    }
}
