<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
        <ApplicationIcon>ClipifyLogo.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AntDesign" />
      <PackageReference Include="MediatR" />
      <PackageReference Include="Microsoft.AspNetCore.Components.WebView.WindowsForms" />
      <PackageReference Include="Microsoft.Extensions.Logging" />
      <PackageReference Include="Microsoft.Extensions.Logging.Debug" />
      <PackageReference Include="xFFmpeg.NET" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="wwwroot\temp\**" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="wwwroot\temp\**" />
    </ItemGroup>

    <ItemGroup>
      <Content Remove="wwwroot\temp\**" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="wwwroot\temp\**" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="wwwroot\temp" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="ClipifyLogo.ico" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Clipify.Core\Clipify.Core.csproj" />
    </ItemGroup>

</Project>
